/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostIndexImport } from './routes/post/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PostPostIdImport } from './routes/post/$postId'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as PostUpdatePostIdImport } from './routes/post/update/$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostIndexRoute = PostIndexImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const PostPostIdRoute = PostPostIdImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const PostUpdatePostIdRoute = PostUpdatePostIdImport.update({
  id: '/post/update/$postId',
  path: '/post/update/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostIndexImport
      parentRoute: typeof rootRoute
    }
    '/post/update/$postId': {
      id: '/post/update/$postId'
      path: '/post/update/$postId'
      fullPath: '/post/update/$postId'
      preLoaderRoute: typeof PostUpdatePostIdImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/post': typeof PostIndexRoute
  '/post/update/$postId': typeof PostUpdatePostIdRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/post': typeof PostIndexRoute
  '/post/update/$postId': typeof PostUpdatePostIdRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/post/': typeof PostIndexRoute
  '/post/update/$postId': typeof PostUpdatePostIdRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/post/$postId'
    | '/dashboard'
    | '/post'
    | '/post/update/$postId'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post/$postId'
    | '/dashboard'
    | '/post'
    | '/post/update/$postId'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/post/$postId'
    | '/dashboard/'
    | '/post/'
    | '/post/update/$postId'
    | '/(auth)/login/'
    | '/(auth)/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostPostIdRoute: typeof PostPostIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PostIndexRoute: typeof PostIndexRoute
  PostUpdatePostIdRoute: typeof PostUpdatePostIdRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostPostIdRoute: PostPostIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PostIndexRoute: PostIndexRoute,
  PostUpdatePostIdRoute: PostUpdatePostIdRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/post/$postId",
        "/dashboard/",
        "/post/",
        "/post/update/$postId",
        "/(auth)/login/",
        "/(auth)/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/post/$postId": {
      "filePath": "post/$postId.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/post/": {
      "filePath": "post/index.tsx"
    },
    "/post/update/$postId": {
      "filePath": "post/update/$postId.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
